### ISSUE TITLE
Consider BSD or MIT licensing

### ISSUE THREAD

**Issue by milancurcic** [leonfoks/coretran#4]
Nice work with coretran.

Would you consider BSD or MIT-like license? GPL is quite restrictive..

**Comment by leonfoks** [comment]
Thank you @milancurcic and of course I just now saw your functional fortran repo, which is great. I had not seen it before, and it is by chance that we have some duplicate routines. Are you still active with that repo?

I had toyed with the idea of using more permissive licenses when I first decided to make this repo public. I read around a bit, and I guess my only reason for using GPL was because I wanted to minimize the amount of forking and having different versions all over the place, and to try to make sure that any enhancements were given back to the community rather than staying behind closed doors if those codes were distributed.

I suppose if I don't care about different versions being out there, and I am content in my original version, then I would technically have no issues releasing under multiple licenses.

Why did you choose BSD-3? and why not GPL? I understand licensing rules, your reasoning would be a great insight.  If you know any good discussions I would love to see them, it's an important topic that new comers consistently have a hard time figuring out.

**Comment by milancurcic** [comment]
I initially started with GPL3 for datetime-fortran. I liked the idea of free software, however, in practice, too many people were asking for more permissive license so they can include it in their project, so I just switched.

Nowadays, I stick with BSD or MIT (MIT is even less strict than BSD) because:

* I want my code to be used in commercial projects.
* Most modern projects use less restrictive licenses. I want my code to be able to be used and redistributed with such projects. So I choose to join them.

There's some good discussions out there, e.g. search the Stack Exchange.

**Comment by milancurcic** [comment]
> Thank you @milancurcic and of course I just now saw your functional fortran repo, which is great. I had not seen it before, and it is by chance that we have some duplicate routines. Are you still active with that repo?

There's at least several folks that use it. I haven't had chance to work much on it recently, but I do have a developing branch to enable most of the functions to work on character strings.

**Comment by mdpiper** [comment]
+1 on this request. I'm always a little hesitant to use GPL-licensed software because IANAL and I'm worried that I may be doing something wrong under the license terms. Like @milancurcic, I'm a fan of the MIT license.

**Comment by leonfoks** [comment]
Yeah using GPL code in any form essentially forces you to release under GPL too as far as i've read. I've been getting a bit more push to release under more permissive licenses, so I think i'll go ahead!
